filetype off " required by Vundle, no more explanation to give

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Utils
Plugin 'tpope/vim-surround'            " surround word/sentence with quotes
Plugin 'airblade/vim-rooter'           " auto-define the root of project
Plugin 'dylanaraps/wal'                " colorscheme based on wal script
Plugin 'ludovicchabant/vim-gutentags'  " ctags
Plugin 'Valloric/YouCompleteMe'        " autocompletion

" Git plugins
Plugin 'tpope/vim-fugitive'            " git commands in vim
Plugin 'airblade/vim-gitgutter'        " git diff for the current file
Plugin 'junegunn/gv.vim'               " git commit browser

" Airline
Plugin 'vim-airline/vim-airline'        " vim status line
Plugin 'vim-airline/vim-airline-themes' " theme for the vim status line

" File extensions
Plugin 'scrooloose/nerdtree'            " file explorer in vim
Plugin 'majutsushi/tagbar'

" Find in path like
Plugin 'rking/ag.vim'                   " the silver searcher implementation
Plugin 'ctrlpvim/ctrlp.vim'             " fuzzy finder

" EditorConfig, Linters
Plugin 'editorconfig/editorconfig-vim'  " editorconfig

" Language plugins
Plugin 'tpope/vim-markdown'
Plugin 'mattn/emmet-vim'               " Emmet for Vim
Plugin 'posva/vim-vue'                 " VueJS support
Plugin 'PotatoesMaster/i3-vim-syntax'  " i3wm syntax highlight
Plugin 'pangloss/vim-javascript'       " javascript improvement
Plugin 'mxw/vim-jsx'                   " JSX support
Plugin 'dag/vim-fish'                  " fish shell support
Plugin 'leafgarland/typescript-vim'    " typescript support

" Syntax checking plugin
Plugin 'w0rp/ale'                     " asynchronous linter

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

source ~/etc/dotfiles/vim/main-config.vim
source ~/etc/dotfiles/vim/ctrlp-config.vim

" Highlight trailing whitespaces
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
match ExtraWhitespace /\s\+$\|\t/

" In Git commit message, let's use 72 characters line-length
autocmd FileType gitcommit set colorcolumn=72

let g:airline_powerline_fonts = 1 " for the status bar to use powerline char
let g:airline_theme='molokai'
let g:airline#extensions#tabline#enabled = 1

" In Insert mode, set the line's numbers
" In the others, set the line's relative numbers
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

"
" Key mapping
"
" imap is for the Insert mode
" nmap is for the Normal mode
"

imap kj <Esc>                   " Map kj as a new escape key
nmap <C-n> :NERDTreeToggle<CR>  " Map Ctrl+n to toggle NERDTree

" Purity
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" ALE Configuration
" INLINE LINTING/TYPE CHECKING/FORMATTING
let g:ale_linters = {}
let g:ale_linters['javascript'] = ['prettier']
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier']
let g:ale_sign_column_always = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 0
let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_use_local_config = 1


" NERDTree Configuration
let NERDTreeShowHidden=1

" vim-jsx Configuration
let g:jsx_ext_required = 0

" YouCompleteMe
let g:ycm_min_num_of_chars_for_completion = 4
let g:ycm_min_num_identifier_candidate_chars = 4
let g:ycm_enable_diagnostic_highlighting = 0

