set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Utils
Plugin 'tpope/vim-surround'            " surround word/sentence with quotes
Plugin 'airblade/vim-rooter'           " auto-define the root of project
Plugin 'enricobacis/vim-airline-clock' " clock in vim-airline
Plugin 'dylanaraps/wal'                " colorscheme based on wal script

" Git plugins
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'junegunn/gv.vim'

" Airline
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" File extensions
Plugin 'scrooloose/nerdtree'
Plugin 'majutsushi/tagbar'

" Find in path like
Plugin 'rking/ag.vim'
Plugin 'ctrlpvim/ctrlp.vim'

" EditorConfig
Plugin 'editorconfig/editorconfig-vim'

" Language plugins
Plugin 'leafgarland/typescript-vim'
Plugin 'IN3D/vim-raml'
Plugin 'lumiliet/vim-twig'
Plugin 'tpope/vim-cucumber'
Plugin 'tpope/vim-markdown'
Plugin 'mattn/emmet-vim'
Plugin 'posva/vim-vue'
Plugin 'PotatoesMaster/i3-vim-syntax'

" Syntax checking plugin
Plugin 'scrooloose/syntastic'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

syntax enable

" Syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" SYNTASTIC CONFIGURATION
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_java_checkers=['javac']
let g:syntastic_java_javac_config_file_enabled = 1

set encoding=utf-8            " set the encoding
set number                    " line numbers
set laststatus=2              " for the status bar to appear all the time
set background=dark           " for the status bar to print correctly on gnome
set tabstop=2 shiftwidth=2 expandtab
set ttyfast                   " send more characters for redraws
set mouse=a                   " enable mouse in all modes
set ttymouse=xterm2           " mouse code for terminal
set colorcolumn=81            " limit line-length to 80 characters
set listchars=tab:→\ ,eol:↲,nbsp:␣,trail:•,extends:⟩,precedes:⟨ " invisible
set backspace=indent,eol,start " make backspace work like most other apps
set autoread

colorscheme wal

" In Git commit message, let's use 72 characters line-length
autocmd FileType gitcommit set colorcolumn=72

let g:airline_powerline_fonts = 1 " for the status bar to use powerline char
let g:airline_theme='term'
let g:airline#extensions#tabline#enabled = 1

" In Insert mode, set the line's numbers
" In the others, set the line's relative numbers
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

"
" Key mapping
"
" imap is for the Insert mode
" nmap is for the Normal mode
"

imap kj <Esc>                   " Map kj as a new escape key
nmap <C-n> :NERDTreeToggle<CR>  " Map Ctrl+n to toggle NERDTree

" Next step fix a leafgarland/typescript-vim bug
autocmd BufNewFile,BufRead *.ts,*.tsx setlocal filetype=typescript

