# ----------------------------------------
# zsh configuration file -- ~/.zshrc
# by Yoann Fleury <yoann.fleury@yahoo.com>
# ----------------------------------------

#{{{ Set up environment

TERM=screen
EDITOR=vim
VISUAL=vim
PATH=$PATH:$HOME/.local/bin:$HOME/bin/java/aspectj1.8/bin
CLASSPATH=$HOME/bin/java/aspectj1.8/lib/aspectjst.jar
XDG_CONFIG_HOME=$HOME/.config

#}}}

#{{{ Set up prompt

autoload -Uz promptinit
promptinit
source ~/.zsh/prompt.zsh

#}}}


#{{{ ZSH Modules

# Enable completion
autoload -Uz compinit
compinit

#}}}

#{{{ OPTIONS

# Auto change directory when typing the name of a directory
setopt auto_cd

# Will correct sl to ls (won't work if you install sl command :])
setopt correct

# Spelling correction for arguments
unsetopt correct_all

# Allow multiple terminal sessions to all append to one zsh history file
setopt append_history

# Save timestamp of command and the duration
setopt extended_history

# Don't write events to history that are duplicates of previous events
setopt hist_ignore_dups

# Remove command line from history list when first character on the line is a space
setopt hist_ignore_space


#}}}

#{{{ ALIAS

source ~/.zsh/aliases.zsh

#}}}

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

zstyle ':completion:*:rm:*' ignore-line yes # Ignore files already present in rm command
zstyle ':completion:*:mv:*' ignore-line yes # Ignore files already present in mv command
zstyle ':completion:*:cp:*' ignore-line yes # Ignore files already present in cp command

#{{{ PLUGINS

# ZSH syntax highlighting plugin
source $HOME/etc/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#}}}
