# ----------------------------------------
# zsh configuration file -- ~/.zshrc
# by Yoann Fleury <yoann.fleury@yahoo.com>
# ----------------------------------------

#{{{ Set up environment

export TERM="screen-256color"
export EDITOR=vim
export VISUAL=vim
export LC_ALL="en_US.UTF-8"

# -- JAVA RELATED --
JAVA_HOME=$HOME/bin/java/jdk
GRADLE_HOME=$HOME/bin/java/gradle-3.1
SPRING_HOME=$HOME/bin/java/spring-1.4.1.RELEASE
ANDROID_HOME=$HOME/bin/android/sdk
MVN_HOME=$HOME/bin/maven
CATALINA_HOME=$HOME/bin/tomcat
# --

# -- DEVELOPMENT RELATED --
export GRAPHVIZ_DOT="/home/yfleury/.linuxbrew/bin/dot"
# --

# -- PATH --
PATH=$HOME/bin:$HOME/.linuxbrew/bin:$PATH:$HOME/.local/bin:$JAVA_HOME/bin:$HOME/bin/java/aspectj1.8/bin:$GRADLE_HOME/bin:$SPRING_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$MVN_HOME/bin:$HOME/dev/go/bin
# --

# -- OTHER PATHS --
MANPATH="/home/yfleury/.linuxbrew/share/man:$MANPATH"
INFOPATH="/home/yfleury/.linuxbrew/share/info:$INFOPATH"
XDG_DATA_DIRS="/home/yfleury/.linuxbrew/share:$XDG_DATA_DIRS"
CLASSPATH=$HOME/bin/java/aspectj1.8/lib/aspectjst.jar
XDG_CONFIG_HOME=$HOME/.config
export GOPATH="$HOME/dev/go"
# --

#}}}

#{{{ Set up prompt

autoload -Uz promptinit
promptinit
source ~/.zsh/prompt.zsh

#}}}


#{{{ ZSH Modules

# Enable autocompletion
autoload -U compinit && compinit
zmodload -i zsh/complist

zstyle ':vcs_info:*' actionformats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{3}|%F{1}%a%F{5}]%f '
zstyle ':vcs_info:*' formats '%F{5}(%f%s%F{5})%F{3}-%F{5}[%F{2}%b%F{5}]%f '
zstyle ':vcs_info:*' enable git



fpath=(path/to/zsh-completions/src $fpath)

#}}}

#{{{ OPTIONS

# ===== DIRECTORIES
# Auto change directory when typing the name of a directory
setopt auto_cd           # if you type foo and it's not a command but a directory in your cdpath, zsh will go there
setopt pushd_ignore_dups # don't push multiple copy

# Will correct sl to ls (won't work if you install sl command :])
setopt correct

# Spelling correction for arguments
unsetopt correct_all

# Allow multiple terminal sessions to all append to one zsh history file
setopt append_history

# Save timestamp of command and the duration
setopt extended_history

# Don't write events to history that are duplicates of previous events
setopt hist_ignore_dups

# Remove command line from history list when first character on the line is a space
setopt hist_ignore_space


#}}}

#{{{ ALIAS

source ~/.zsh/aliases.zsh

#}}}

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

zstyle ':completion:*:rm:*' ignore-line yes # Ignore files already present in rm command
zstyle ':completion:*:mv:*' ignore-line yes # Ignore files already present in mv command
zstyle ':completion:*:cp:*' ignore-line yes # Ignore files already present in cp command

#{{{ KEY BINDINGS

bindkey '^R' history-incremental-search-backward
bindkey '^A' beginning-of-line
bindkey '^I' end-of-line

#}}}

#{{{ COLORS
autoload colors; colors
#}}}

#{{{ PLUGINS

# ZSH syntax highlighting plugin
source $HOME/etc/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ZSH k plugin (https://github.com/supercrabtree/k)
source $HOME/etc/k/k.sh

# ZSH autosuggestion plugin (https://github.com/zsh-users/zsh-autosuggestions)
source $HOME/etc/zsh-autosuggestions/zsh-autosuggestions.zsh

#}}}
