# ----------------------------------------
# zsh configuration file -- ~/.zshrc
# by Yoann Fleury <yoann.fleury@yahoo.com>
# ----------------------------------------

# ENVIRONMENT SETUP {{{

export TERM="screen-256color"
export TERMINAL=termite
export EDITOR=vim
export BROWSER=chromium
export VISUAL=vim
export LC_ALL="en_US.UTF-8"

# -- JAVA RELATED --
export JAVA_HOME=$HOME/bin/java/jdk
export GRADLE_HOME=$HOME/bin/java/gradle
export GRADLE_USER_HOME=$HOME/.gradle
export SPRING_HOME=$HOME/bin/java/spring-1.4.1.RELEASE
export ANDROID_HOME=$HOME/bin/android/sdk
export MVN_HOME=$HOME/bin/maven
export CATALINA_HOME=$HOME/bin/tomcat
# --

# -- PATH --
export PATH=$HOME/bin:$HOME/.linuxbrew/bin:$PATH:$HOME/.local/bin:$JAVA_HOME/bin:$HOME/bin/java/aspectj1.8/bin:$GRADLE_HOME/bin:$SPRING_HOME/bin:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$MVN_HOME/bin:$HOME/dev/go/bin

if hash yarn 2>/dev/null; then
  export PATH=$PATH:$(yarn global bin)
fi
# --



# -- OTHER PATHS --
export MANPATH="/home/yfleury/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/yfleury/.linuxbrew/share/info:$INFOPATH"
export XDG_DATA_DIRS="/home/yfleury/.linuxbrew/share:$XDG_DATA_DIRS"
export CLASSPATH=$HOME/bin/java/aspectj1.8/lib/aspectjst.jar
export XDG_CONFIG_HOME=$HOME/.config
export GOPATH="$HOME/dev/go"
fpath=(~/.zsh/completion $fpath)
# --

# }}}

# PROMPT {{{

autoload -Uz promptinit
promptinit
source $HOME/.zsh/prompt.zsh

# }}}

# OPTIONS {{{

# ===== DIRECTORIES
# Auto change directory when typing the name of a directory
# if you type foo and it's not a command but a directory in your cdpath, zsh will go there
setopt auto_cd
# don't push multiple copy
setopt pushd_ignore_dups

# ===== AUTOCORRECT
# Will correct sl to ls (won't work if you install sl command :])
setopt correct
# Spelling correction for arguments
unsetopt correct_all

# ===== HISTORY
# Allow multiple terminal sessions to all append to one zsh history file
setopt append_history
# Save timestamp of command and the duration
setopt extended_history
# Add commands as they are typed, don't wait until shell exit
setopt inc_append_history
# When trimming history, lose oldest duplicates first
setopt hist_expire_dups_first
# Don't write events to history that are duplicates of previous events
setopt hist_ignore_dups
# Remove command line from history list when first character on the line is a space
setopt hist_ignore_space
# When searching history, don't display results already cycled through twice
setopt hist_find_no_dups
# Remove extra blanks from each command line being added to history
setopt hist_reduce_blanks
# Don't execute, just expand history
setopt hist_verify
# Imports new commands and appends typed commands to history
setopt share_history

setopt histignorealldups

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=9000
HISTFILE=~/.zsh_history

# Use emacs keybindings even if EDITOR is set to vi
bindkey -e

# }}}


# ALIAS {{{

source ~/.zsh/aliases.zsh

# }}}

# WORK {{{

if [[ -f $HOME/.zsh/work_configuration.zsh ]]; then
  source $HOME/.zsh/work_configuration.zsh
fi

# }}}

# PLUGINS {{{

# ZSH syntax highlighting plugin
if [[ -f $HOME/etc/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
  source $HOME/etc/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# ZSH k plugin (https://github.com/supercrabtree/k)
if [[ -f $HOME/etc/k/k.sh ]]; then
  source $HOME/etc/k/k.sh
fi

# ZSH autosuggestion plugin (https://github.com/zsh-users/zsh-autosuggestions)
if [[ -f $HOME/etc/zsh-autosuggestions/zsh-autosuggestions.zsh ]]; then
  source $HOME/etc/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

if [[ -f $HOME/etc/z/z.sh ]]; then
  source $HOME/etc/z/z.sh
fi

# }}}

# COMPLETION {{{

autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# }}}

# Get the TMUX ID panes
export TMUX_ID="$((`tmux display -pt "${TMUX_PANE:?}" "#{pane_index}"` + 1))" 2> /dev/null

# COLORSCHEME {{{
(wal -r &)
# }}}
