#!/usr/bin/env bash

FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)

for file in $FILES; do
  if echo ${file} | grep "properties"; then
    echo -e "\e[41m                                                       \e[0m"
    echo -e "\e[41m You just changed an important file, be sure           \e[0m"
    echo -e "\e[41m everything is done                                    \e[0m"
    echo -e "\e[41m                                                       \e[0m"
  fi
done

